

export const CREATE_STUDENT_BEGIN = 'CREATE_STUDENT_BEGIN'
export const CREATE_STUDENT_SUCCESS = 'CREATE_STUDENT_SUCCESS'
export const CREATE_STUDENT_ERROR = 'CREATE_STUDENT_ERROR'

export const GET_STUDENT_BEGIN = 'GET_STUDENT_BEGIN'
export const GET_STUDENT_SUCCESS = 'GET_STUDENT_SUCCESS'
export const GET_STUDENT_ERROR = 'GET_STUDENT_ERROR'